gemfile: Gemfile

PreCommit:
  # Dependency Check
  BundleCheck:
    enabled: true
    on_warn: fail

  # Javascript check
  EsLint:
    enabled: true
    command: ['./node_modules/.bin/eslint', '-c', 'config/.eslintrc.json']
    required_executable: './node_modules/.bin/eslint'
    include: 'source/javascripts/**/*.js'

  # HAML check
  HamlLint:
    enabled: true
    command: ['bundle', 'exec', 'haml-lint', '-c', 'config/.haml-lint.yml', 'source/']
    on_warn: fail

  # Ruby check
  RuboCop:
    enabled: true
    command: ['bundle', 'exec', 'rubocop', '-c', 'config/.rubocop.yml']
    problem_on_unmodified_line: warn

  # Sass check
  ScssLint:
    enabled: true
    command: ['bundle', 'exec', 'scss-lint', '-c', 'config/.scss-lint.yml', 'source/stylesheets/']
    on_warn: fail

  # YAML check
  YamlSyntax:
    enabled: true
    on_warn: fail

PrePush:
  BundleInstall:
    enabled: true
    on_warn: fail

  # Unit & Integration tests
  RSpec:
    enabled: true
    command: ['bundle', 'exec', 'rspec', 'spec']
    on_warn: fail

  ProtectedBranches:
    enabled: true
    branches: ['master']