repos:
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.31.0
    hooks:
      - id: terraform_docs
        args: ['--args=--sort-by-required']
      - id: terraform_fmt
      - id: terraform_tflint
        args: ['--args=--deep --module']
        exclude: ^examples
      # - id: terraform_tfsec
      - id: terraform_validate
        exclude: ^examples
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: trailing-whitespace
