# baseurl = "http://mdzhang.com/"
languageCode = "en-US"
title = "M D Zhang"
theme = "sam"
googleAnalytics = "UA-66633424-1"

# for theme

[params]
  email = "md.zhang.aka@gmail.com"
  favicon = "favicon.ico"
  firstName = "M"
  footerText = "say hi."
  homepage = "a place called home"
  lastName = "Zhang"
  title = "M D Zhang"

[[params.mainMenu]]
  link = "about"
  text = "i'm m"

[[params.mainMenu]]
  link = "thoughts"
  text = "here are some thoughts"

[imaging]
  quality = 75
