# baseurl = "http://mdzhang.com/"
languageCode = "en-US"
title = "M D Zhang"
theme = "cactus"
googleAnalytics = "UA-66633424-1"

# for theme

[params]

  colortheme = "white"
  description = "Hi 👋, I'm Meesh."
  googleAnalyticsAsync = true
  rss = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4
