# baseurl = "http://mdzhang.com/"
languageCode = "en-US"
title = "Michelle D Zhang"
theme = "sam"
googleAnalytics = "UA-66633424-1"

# for theme

[params]
  address = "New York City, NY"
  email = "zhang.michelle.d@gmail.com"
  favicon = "favicon.ico"
  firstName = "Michelle"
  footerText = "say hi."
  homepage = "a place called home"
  lastName = "Zhang"
  phone = "1-201-290-4969"
  profileImage = "https://s.gravatar.com/avatar/6ec7da55967198680c3c4c81f880ab0c?s=160"
  title = "Michelle D Zhang"

[[params.mainMenu]]
  link = "about"
  text = "i'm michelle"

[[params.mainMenu]]
  link = "thoughts"
  text = "here are some thoughts"

[imaging]
  quality = 75
