# baseurl = "http://mdzhang.com/"
languageCode = "en-US"
title = "Michelle D Zhang"
theme = "hugo-sustain"
disqusShortname = "mdzhang"
googleAnalytics = "UA-66633424-1"

# for theme
[params]
  avatar = "https://s.gravatar.com/avatar/6ec7da55967198680c3c4c81f880ab0c?s=160"
  author = "Michelle D Zhang"
  locale = "en-US"
  description = "Michelle D Zhang Personal Site"
  shortBio = "I currently work remotely for Flashpoint, a business risk intelligence firm"

[params.social]
  Github        = "mdzhang"
  Email         = "zhang.michelle.d@gmail.com"
  LinkedIn      = "mdzhang"
