version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    working_directory: ~/repo

    branches:
      only:
        - master
        - development

    steps:
      - checkout

      # install hugo theme repo
      - run: git submodule init && git submodule update --init --recursive

      # install and cache node dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # install hugo
      - run: wget https://github.com/gohugoio/hugo/releases/download/v0.36/hugo_0.36_Linux-64bit.deb && sudo dpkg -i hugo*.deb

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo 'export HUGO_BASEURL=http://mdzhang.com/' >> $BASH_ENV
              echo 'export AWS_S3_BUCKET=mdzhang.com' >> $BASH_ENV
            fi

            if [ "${CIRCLE_BRANCH}" == "development" ]; then
              echo 'export HUGO_BASEURL=http://staging-1.mdzhang.com/' >> $BASH_ENV
              echo 'export AWS_S3_BUCKET=staging-1.mdzhang.com' >> $BASH_ENV
            fi

            hugo
            yarn deploy
