version: 2
defaults: &defaults
  working_directory: ~/opt/mdzhang/mdzhang.com
  docker:
    - image: circleci/node:8.9.2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-yarn
          command: curl -o- -L https://yarnpkg.com/install.sh | bash
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: yarn-node-gyp-fix
          command: yarn global add node-gyp
      - run:
          name: install-deps
          command: yarn install
      - run:
          name: build-app
          command: ./node_modules/.bin/gatsby build
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths: public
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/opt/mdzhang/mdzhang.com/public
      - run:
          name: build-and-push-to-s3
          command: |
            if [ "${CIRCLE_BRANCH}" == "development" ]; then
              NODE_ENV=staging make deploy;
            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
              NODE_ENV=production make deploy;
            fi

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - development
