---
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.20.0
    working_directory: ~/repo

    branches:
      only:
        - master
        - development
        - feature/circle

    steps:
      - checkout

      # install hugo theme repo
      - run: git submodule init && git submodule update --init --recursive

      # install and cache node dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # install hugo
      - run: wget https://github.com/gohugoio/hugo/releases/download/v0.80.0/hugo_0.80.0_Linux-64bit.deb && sudo dpkg -i hugo*.deb

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              export HUGO_BASEURL=http://mdzhang.com/
              export AWS_S3_BUCKET=mdzhang.com
            fi

            if [ "${CIRCLE_BRANCH}" == "development" ]; then
              export HUGO_BASEURL=http://staging-1.mdzhang.com/
              export AWS_S3_BUCKET=staging-1.mdzhang.com
              echo $'User-agent: *\nDisallow: /' > static/robots.txt
            fi

            npm install -g postcss-cli
            npm install -g autoprefixer
            hugo
            npm run deploy
