AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/config.ru'
    - '**/Rakefile'
    - '**/Gemfile'
    - './bin/rake'
    - './bin/setup'
    - '**/*.rake'

Metrics/BlockLength:
  Max: 50

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 60

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
