name: deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          # fetch hugo themes
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.101.0'
          # avoid postcss issues
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy to staging
        if: github.ref == 'refs/heads/development'
        run: |
          aws s3 sync --acl public-read ./public s3://$HUGO_BASEURL
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-west-1'
          HUGO_BASEURL: staging-1.mdzhang.com

      - name: Deploy to prod
        if: github.ref == 'refs/heads/master'
        run: |
          aws s3 sync --acl public-read ./public s3://$HUGO_BASEURL
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-west-1'
          HUGO_BASEURL: mdzhang.com
