# Adapted from https://github.com/marketplace/actions/hashicorp-setup-terraform
# Actual Terraform plans occur through the Terraform/GitHub OAuth connection
name: terraform

on:
  push:
    branches:
      - main
    paths:
      # sync this w/ TF Cloud
      - 'terraform/**'
      - '.github/workflows/terraform.yml'
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'

jobs:
  format_and_validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'terraform'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          # sync this w/ TF Cloud
          terraform_version: 1.5.5

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init -input=false -backend=false

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
